### ISSUE TITLE
Submission of rating is disabled in IOS.

### ISSUE THREAD

**Issue by deligence** [Skyost/rate_my_app#1]
**Describe the bug**
In IOS, submit button is disabled.

**Screenshots**
![IMG_0173](https://user-images.githubusercontent.com/8718725/57014391-81e35c00-6c2d-11e9-871a-efb356c397bf.PNG)

**Smartphone**
Iphone 7+ IOS (11.3.1)

**Comment by Skyost** [comment]
Is your app published on the App Store ? Do you have entered correct info in your Info.plist ?

**Comment by Skyost** [comment]
Is your app published on the App Store ? Do you have entered correct info in your Info.plist ?

**Comment by deligence** [comment]
Yes the app is published on the App store and I have followed all the step mentioned by you.

**Comment by Skyost** [comment]
Are you running your app in release mode ? Because :

1. When building in XCode, you will see what the OP shows in the screenshot
2. When building from a CI solution for release, you will not see anything
3. When running from TestFlight, you will not see anything
4. When running from the AppStore, only users who purchased (free or paid) your app will see it [up to three times a year](https://developer.apple.com/app-store/ratings-and-reviews/)
5. When running from the AppStore, users who obtain your app via Connect promo codes [will not see it](https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Chapters/ProvidingPromoCodes.html)
6. Users who disable **In-App Ratings & Reviews** under **iTunes & App Stores** in the **Settings** app will never see these prompts under any condition

([Source](https://stackoverflow.com/questions/45057452/why-the-skstorereviewcontroller-does-not-let-me-submit-a-review))

**Comment by Skyost** [comment]
Closed as the author doesn't seem to respond anymore.

**Comment by Xoshbin** [comment]
Is there any solution? I'm having the same issue on iPhone 6S in debug mode and release mode too.

**Comment by Skyost** [comment]
@Xoshbin Does it happen even when you download your app from the App Store ?

**Comment by Xoshbin** [comment]
I didn't try that yet. But on Android studio running on both profile mode and release mode, the submit button is disabled.

**Comment by Skyost** [comment]
And is your app published on the app store ?

**Comment by Xoshbin** [comment]
@Skyost After downloading the app from app store it works well without issues.

**Comment by Skyost** [comment]
Fine then ! 😃

**Comment by dungnc** [comment]
> Are you running your app in release mode ? Because :
> 
> 1. When building in XCode, you will see what the OP shows in the screenshot
> 2. When building from a CI solution for release, you will not see anything
> 3. When running from TestFlight, you will not see anything
> 4. When running from the AppStore, only users who purchased (free or paid) your app will see it [up to three times a year](https://developer.apple.com/app-store/ratings-and-reviews/)
> 5. When running from the AppStore, users who obtain your app via Connect promo codes [will not see it](https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Chapters/ProvidingPromoCodes.html)
> 6. Users who disable **In-App Ratings & Reviews** under **iTunes & App Stores** in the **Settings** app will never see these prompts under any condition
> 
> ([Source](https://stackoverflow.com/questions/45057452/why-the-skstorereviewcontroller-does-not-let-me-submit-a-review))

Will the rate app dialog open when I download on TestFlight?

**Comment by Skyost** [comment]
> Will the rate app dialog open when I download on TestFlight?

I really don't know as I'm not using TestFlight.

> If not, will the dialog show when I downlaod app on AppStore?

Yep !
